/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Gui;

import controlladores.ClienteJpaController;
import Data.Cliente;
import Data.ModeloExcel;
import java.awt.Image;
import java.io.File;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.List;
import javax.persistence.EntityManager;
import javax.persistence.EntityManagerFactory;
import javax.persistence.Persistence;
import javax.persistence.TypedQuery;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Theking
 */
public class Ingresos extends javax.swing.JFrame {
    Date fecha = new Date();
    SimpleDateFormat format = new SimpleDateFormat("dd-MM-yyyy");
    String date = format.format(fecha);
    
    File archivo;
    JFileChooser selecArchivo = new JFileChooser();
    
    int contAccion = 0;
    DefaultTableModel modelo;

    public Ingresos() {
        initComponents();

        Image icon = new ImageIcon(getClass().getResource("/img/icon.jpg")).getImage();
        setIconImage(icon);

        this.setExtendedState(MAXIMIZED_BOTH);
        this.setDefaultCloseOperation(this.DO_NOTHING_ON_CLOSE);
        
        tf_fecha.setText(date);
        //limpiar();
        modelarTabla();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        Entity = java.beans.Beans.isDesignTime() ? null : javax.persistence.Persistence.createEntityManagerFactory("LipiAppPU").createEntityManager();
        em = java.beans.Beans.isDesignTime() ? null : javax.persistence.Persistence.createEntityManagerFactory("LipiAppPU").createEntityManager();
        jPanel5 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        tf_buscar = new javax.swing.JTextField();
        bt_buscar = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        lb_id = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        tf_factura = new javax.swing.JTextField();
        tf_rut = new javax.swing.JTextField();
        tf_nombre = new javax.swing.JTextField();
        tf_domicilio = new javax.swing.JTextField();
        tf_valor = new javax.swing.JTextField();
        tf_fecha = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabla_cliente = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        tf_5k = new javax.swing.JTextField();
        tf_11k = new javax.swing.JTextField();
        tf_15k = new javax.swing.JTextField();
        tf_45k = new javax.swing.JTextField();
        tf_15kal = new javax.swing.JTextField();
        tf_15kFe = new javax.swing.JTextField();
        tf_5kc = new javax.swing.JTextField();
        tf_15kc = new javax.swing.JTextField();
        tf_45kc = new javax.swing.JTextField();
        tf_11kc = new javax.swing.JTextField();
        bt_guardar = new javax.swing.JButton();
        bt_eliminar = new javax.swing.JButton();
        bt_editar = new javax.swing.JButton();
        bt_guardarcambios = new javax.swing.JButton();
        bt_exportar = new javax.swing.JButton();
        bt_importar = new javax.swing.JButton();
        bt_limpiar = new javax.swing.JButton();

        jLabel2.setText("jLabel2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("LipiApp");
        setName("Ingreso de clientes"); // NOI18N
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        jLabel10.setText("Buscar Cliente");

        tf_buscar.setToolTipText("Ingrese RUT sin puntos ni guion");
        tf_buscar.setMaximumSize(new java.awt.Dimension(9, 9));

        bt_buscar.setText("Buscar");
        bt_buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_buscarActionPerformed(evt);
            }
        });

        lb_id.setEnabled(false);
        lb_id.setOpaque(true);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addComponent(lb_id, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lb_id, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(93, 93, 93)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(76, 76, 76)
                .addComponent(tf_buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(bt_buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap(29, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(tf_buscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt_buscar))
                .addGap(14, 14, 14))
            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jLabel1.setText("Fecha");

        jLabel3.setText("Numero Factura");

        jLabel4.setText("RUT");

        jLabel5.setText("Nombre completo");

        jLabel6.setText("Domicilio");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel7.setText("Valor de Factura");

        tf_factura.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tf_facturaKeyTyped(evt);
            }
        });

        tf_valor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tf_valorKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(96, 96, 96)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel3)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(65, 65, 65)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tf_fecha)
                    .addComponent(tf_domicilio, javax.swing.GroupLayout.DEFAULT_SIZE, 240, Short.MAX_VALUE)
                    .addComponent(tf_nombre)
                    .addComponent(tf_rut)
                    .addComponent(tf_factura)
                    .addComponent(tf_valor))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tf_fecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(tf_factura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(tf_rut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(tf_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(tf_domicilio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(tf_valor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        tabla_cliente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Fecha", "N° Factura", "RUT", "Nombre", "Domicilio", "Valor Factura", "5k", "11k", "15k", "45k", "15k Al", "15k FE", "5K C", "11k C", "15k C", "45kC"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabla_cliente.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        tabla_cliente.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(tabla_cliente);
        if (tabla_cliente.getColumnModel().getColumnCount() > 0) {
            tabla_cliente.getColumnModel().getColumn(0).setResizable(false);
            tabla_cliente.getColumnModel().getColumn(1).setResizable(false);
            tabla_cliente.getColumnModel().getColumn(2).setResizable(false);
            tabla_cliente.getColumnModel().getColumn(3).setResizable(false);
            tabla_cliente.getColumnModel().getColumn(4).setResizable(false);
            tabla_cliente.getColumnModel().getColumn(5).setResizable(false);
            tabla_cliente.getColumnModel().getColumn(6).setResizable(false);
            tabla_cliente.getColumnModel().getColumn(7).setResizable(false);
            tabla_cliente.getColumnModel().getColumn(8).setResizable(false);
            tabla_cliente.getColumnModel().getColumn(9).setResizable(false);
            tabla_cliente.getColumnModel().getColumn(10).setResizable(false);
            tabla_cliente.getColumnModel().getColumn(11).setResizable(false);
            tabla_cliente.getColumnModel().getColumn(12).setResizable(false);
            tabla_cliente.getColumnModel().getColumn(13).setResizable(false);
            tabla_cliente.getColumnModel().getColumn(14).setResizable(false);
            tabla_cliente.getColumnModel().getColumn(15).setResizable(false);
            tabla_cliente.getColumnModel().getColumn(16).setResizable(false);
        }

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 1317, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        jLabel12.setText("5k");
        jLabel12.setPreferredSize(new java.awt.Dimension(40, 14));

        jLabel13.setText("11k");
        jLabel13.setPreferredSize(new java.awt.Dimension(40, 14));

        jLabel14.setText("15k");
        jLabel14.setPreferredSize(new java.awt.Dimension(40, 14));

        jLabel15.setText("45k");
        jLabel15.setPreferredSize(new java.awt.Dimension(40, 14));

        jLabel16.setText("15k Al");
        jLabel16.setPreferredSize(new java.awt.Dimension(40, 14));

        jLabel17.setText("15k FE");
        jLabel17.setPreferredSize(new java.awt.Dimension(40, 14));

        jLabel18.setText("5k C");
        jLabel18.setPreferredSize(new java.awt.Dimension(40, 14));

        jLabel19.setText("11k C");
        jLabel19.setPreferredSize(new java.awt.Dimension(40, 14));

        jLabel20.setText("15k C");
        jLabel20.setPreferredSize(new java.awt.Dimension(40, 14));

        jLabel21.setText("45k C");
        jLabel21.setPreferredSize(new java.awt.Dimension(40, 14));

        tf_5k.setText("0");
        tf_5k.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tf_5kKeyTyped(evt);
            }
        });

        tf_11k.setText("0");
        tf_11k.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tf_11kKeyTyped(evt);
            }
        });

        tf_15k.setText("0");
        tf_15k.setToolTipText("");
        tf_15k.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tf_15kKeyTyped(evt);
            }
        });

        tf_45k.setText("0");
        tf_45k.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tf_45kKeyTyped(evt);
            }
        });

        tf_15kal.setText("0");
        tf_15kal.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tf_15kalKeyTyped(evt);
            }
        });

        tf_15kFe.setText("0");
        tf_15kFe.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tf_15kFeKeyTyped(evt);
            }
        });

        tf_5kc.setText("0");
        tf_5kc.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tf_5kcKeyTyped(evt);
            }
        });

        tf_15kc.setText("0");
        tf_15kc.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tf_15kcKeyTyped(evt);
            }
        });

        tf_45kc.setText("0");
        tf_45kc.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tf_45kcKeyTyped(evt);
            }
        });

        tf_11kc.setText("0");
        tf_11kc.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tf_11kcKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(91, 91, 91)
                .addComponent(tf_5k, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(tf_11k, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(tf_15k, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(tf_45k, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21)
                .addComponent(tf_15kal, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(tf_15kFe, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(tf_5kc, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(tf_11kc, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(tf_15kc, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(tf_45kc, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(2, 2, 2)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf_11k, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_5k, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_15k, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_45k, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_15kal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_15kFe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_5kc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_15kc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_45kc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_11kc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        bt_guardar.setBackground(new java.awt.Color(165, 165, 221));
        bt_guardar.setText("Guardar Información");
        bt_guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_guardarActionPerformed(evt);
            }
        });

        bt_eliminar.setBackground(new java.awt.Color(213, 158, 158));
        bt_eliminar.setText("Eliminar Información ");
        bt_eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_eliminarActionPerformed(evt);
            }
        });

        bt_editar.setText("Editar Información");
        bt_editar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_editarActionPerformed(evt);
            }
        });

        bt_guardarcambios.setText("Guardar cambios");
        bt_guardarcambios.setEnabled(false);
        bt_guardarcambios.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bt_guardarcambios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_guardarcambiosActionPerformed(evt);
            }
        });

        bt_exportar.setText("Exportar a  Excel");
        bt_exportar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_exportarActionPerformed(evt);
            }
        });

        bt_importar.setText("Importar desde Excel");
        bt_importar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_importarActionPerformed(evt);
            }
        });

        bt_limpiar.setText("Limpiar");
        bt_limpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_limpiarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(bt_guardar, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bt_eliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(bt_editar, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bt_guardarcambios, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(260, 260, 260)
                .addComponent(bt_limpiar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bt_importar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bt_exportar, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(58, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                .addGap(94, 94, 94)
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21)
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23)
                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21)
                .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(jPanel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bt_guardar)
                    .addComponent(bt_eliminar)
                    .addComponent(bt_editar)
                    .addComponent(bt_guardarcambios)
                    .addComponent(bt_exportar)
                    .addComponent(bt_importar)
                    .addComponent(bt_limpiar))
                .addGap(313, 313, 313))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tf_facturaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf_facturaKeyTyped
        soloNumeros(evt);
    }//GEN-LAST:event_tf_facturaKeyTyped

    private void tf_valorKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf_valorKeyTyped
        soloNumeros(evt);
    }//GEN-LAST:event_tf_valorKeyTyped

    private void bt_buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_buscarActionPerformed
        buscarCliente();
    }//GEN-LAST:event_bt_buscarActionPerformed

    private void bt_eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_eliminarActionPerformed
        eliminarRegistro();
    }//GEN-LAST:event_bt_eliminarActionPerformed

    private void bt_guardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_guardarActionPerformed
        guardarRegistro();
    }//GEN-LAST:event_bt_guardarActionPerformed

    private void tf_11kcKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf_11kcKeyTyped
        soloNumeros(evt);
    }//GEN-LAST:event_tf_11kcKeyTyped

    private void tf_45kcKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf_45kcKeyTyped
        soloNumeros(evt);
    }//GEN-LAST:event_tf_45kcKeyTyped

    private void tf_15kcKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf_15kcKeyTyped
        soloNumeros(evt);
    }//GEN-LAST:event_tf_15kcKeyTyped

    private void tf_5kcKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf_5kcKeyTyped
        soloNumeros(evt);
    }//GEN-LAST:event_tf_5kcKeyTyped

    private void tf_15kFeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf_15kFeKeyTyped
        soloNumeros(evt);
    }//GEN-LAST:event_tf_15kFeKeyTyped

    private void tf_15kalKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf_15kalKeyTyped
        soloNumeros(evt);
    }//GEN-LAST:event_tf_15kalKeyTyped

    private void tf_45kKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf_45kKeyTyped
        soloNumeros(evt);
    }//GEN-LAST:event_tf_45kKeyTyped

    private void tf_15kKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf_15kKeyTyped
        soloNumeros(evt);
    }//GEN-LAST:event_tf_15kKeyTyped

    private void tf_11kKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf_11kKeyTyped
        soloNumeros(evt);
    }//GEN-LAST:event_tf_11kKeyTyped

    private void tf_5kKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf_5kKeyTyped
        soloNumeros(evt);
    }//GEN-LAST:event_tf_5kKeyTyped

    private void bt_editarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_editarActionPerformed
        try {
            ClienteJpaController jpa = new ClienteJpaController(em.getEntityManagerFactory());
            int select = tabla_cliente.getSelectedRow();
            String comp = tabla_cliente.getValueAt(tabla_cliente.getSelectedRow(), 0).toString();
            if (select != -1 & comp != null) {
                bt_guardarcambios.setEnabled(true);
                bt_guardar.setEnabled(false);
                bt_editar.setEnabled(false);
                bt_eliminar.setEnabled(false);
                int id = Integer.parseInt(tabla_cliente.getValueAt(tabla_cliente.getSelectedRow(), 0).toString());
                Cliente c = new Cliente();
                c = jpa.findCliente(id);
                cargarRegistro(c);
            } else {
                JOptionPane.showMessageDialog(null, "Seleccione un registro de la lista");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Seleccione un registro de la lista");
        }
    }//GEN-LAST:event_bt_editarActionPerformed

    private void bt_guardarcambiosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_guardarcambiosActionPerformed
        if (validarVacio()!= 0) {
            Object[] opciones = {"Guardar", "Cancelar"};
            int eleccion = JOptionPane.showOptionDialog(rootPane, "¿Desea guardar cambios?", "Mensaje de Confirmacion",
                    JOptionPane.YES_NO_OPTION,
                    JOptionPane.QUESTION_MESSAGE, null, opciones, "Aceptar");
            if (eleccion == JOptionPane.YES_OPTION) {
                try {
                    ClienteJpaController clienteController = new ClienteJpaController(Entity.getEntityManagerFactory());
                    Cliente cli = new Cliente();
                    cli.setId(Integer.parseInt(modelo.getValueAt(tabla_cliente.getSelectedRow(), 0).toString()));
                    cli.setFecha(tf_fecha.getText());
                    cli.setFactura(tf_factura.getText());
                    cli.setRut(tf_rut.getText());
                    cli.setNombre(tf_nombre.getText());
                    cli.setDomicilio(tf_domicilio.getText());
                    cli.setValorFactura(Integer.parseInt(tf_valor.getText()));
                    cli.setK(tf_5k.getText());
                    cli.setK1(tf_11k.getText());
                    cli.setK2(tf_15k.getText());
                    cli.setK3(tf_45k.getText());
                    cli.setKAl(tf_15kal.getText());
                    cli.setKFe(tf_15kFe.getText());
                    cli.setKCat(tf_5kc.getText());
                    cli.setKCat1(tf_11kc.getText());
                    cli.setKCat2(tf_15kc.getText());
                    cli.setKCat3(tf_45kc.getText());
                    clienteController.edit(cli);
                    editarRegistro(cli);
                    limpiar();
                    bt_guardarcambios.setEnabled(false);
                    bt_guardar.setEnabled(true);
                    bt_editar.setEnabled(true);
                    bt_eliminar.setEnabled(true);
                } catch (Exception e) {
                    if (e.equals(e)) {
                        JOptionPane.showMessageDialog(this, "Existen Campos vacios, por favor revisa tu información!"+e.getMessage());
                    }
                }
            }
        } else {
            JOptionPane.showMessageDialog(this, "Existen Campos vacios, por favor revisa tu información!");
        }
    }//GEN-LAST:event_bt_guardarcambiosActionPerformed

    private void bt_exportarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_exportarActionPerformed
        int rows = tabla_cliente.getRowCount();
        if (rows > 0) {
            ModeloExcel modeloE = new ModeloExcel();
            boolean salir = false;
            contAccion++;
            if (contAccion == 1) {
                AgregarFiltro();
            }
            selecArchivo.setSelectedFile(new File(nombreExcel()));
            archivo =  new File(selecArchivo.getCurrentDirectory()+"\\"+nombreExcel());
            //Aqui se ejecuta la ventana...
            while (salir == false){
                if (selecArchivo.showSaveDialog(null) == JFileChooser.APPROVE_OPTION) {
                    selecArchivo.setSelectedFile(selecArchivo.getSelectedFile());
                    archivo = selecArchivo.getSelectedFile();
                    if (archivo.getName().endsWith("xls") || archivo.getName().endsWith("xlsx")) {
                        //Esta linea llama al método que crea el archivo
                        if (!archivo.exists() & !archivo.isFile()) {
                            JOptionPane.showMessageDialog(null, modeloE.Exportar(archivo, tabla_cliente) + "\nFormato ."
                                + archivo.getName().substring(archivo.getName().lastIndexOf(".") + 1));
                            salir = true;
                        } else {
                            if (JOptionPane.showConfirmDialog(null, "Archivo existente.\n ¿Desea reemplazar?", "Archivo existente", JOptionPane.OK_CANCEL_OPTION, JOptionPane.QUESTION_MESSAGE)== 0 ) {
                                JOptionPane.showMessageDialog(null, modeloE.Exportar(archivo, tabla_cliente) + "\nFormato ."
                                + archivo.getName().substring(archivo.getName().lastIndexOf(".") + 1));
                                salir = true;
                            }
                        }
                    } else {
                        JOptionPane.showMessageDialog(null, "Elija un formato válido.");
                    }
                } else {
                    salir = true;
                }
            }
        } else {
            JOptionPane.showMessageDialog(null, "No hay registros a exportar.");
        }
    }//GEN-LAST:event_bt_exportarActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        exit();
    }//GEN-LAST:event_formWindowClosing

    private void bt_importarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_importarActionPerformed
        String error = "Elija un archivo válido.";
        ModeloExcel modeloE = new ModeloExcel();
        boolean salir = false;
        contAccion++;
        if (contAccion == 1) {
            AgregarFiltro();
        }

        //Aqui se ejecuta la ventana...
        while (salir == false){
            if (selecArchivo.showOpenDialog(null) == JFileChooser.APPROVE_OPTION) {
                archivo =  new File(selecArchivo.getSelectedFile().getAbsolutePath());
                if (archivo.getName().endsWith("xls") || archivo.getName().endsWith("xlsx")) {
                    //Esta linea llama al método que crea el archivo
                    if (archivo.exists() && archivo.isFile()) {
                        JOptionPane.showMessageDialog(null, modeloE.Importar(archivo, tabla_cliente, modelo) + "\nFormato ."
                            + archivo.getName().substring(archivo.getName().lastIndexOf(".") + 1));
                        salir = true;
                    } else {
                        JOptionPane.showMessageDialog(null, error);
                    }
                } else {
                    JOptionPane.showMessageDialog(null, error);
                }
            } else {
                salir = true;
            }
        }
    }//GEN-LAST:event_bt_importarActionPerformed

    private void bt_limpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_limpiarActionPerformed
        int fila = tabla_cliente.getRowCount();
        if (fila > 0) {
            for (int i = 0; i < tabla_cliente.getRowCount(); i++) {
                modelo.removeRow(i);
                i -= 1;
            }
            JOptionPane.showMessageDialog(null, "Datos limpiados correctamente");
        }else{
              JOptionPane.showMessageDialog(null, "No existen datos en la tabla");
                    }
        modelarTabla();
    }//GEN-LAST:event_bt_limpiarActionPerformed

    public String nombreExcel() {
        String[] strMonths = new String[]{
            "Enero",
            "Febrero",
            "Marzo",
            "Abril",
            "Mayo",
            "Junio",
            "Julio",
            "Agosto",
            "Septiembre",
            "Octubre",
            "Noviembre",
            "Diciembre"};
        Calendar cal = Calendar.getInstance();
        int anio = cal.get(Calendar.YEAR);
        //int anio = fecha.getYear();
        String mes = strMonths[fecha.getMonth()];
        String out = anio +" "+ mes + ".xls";
        return out;
    }
    
    public void AgregarFiltro() {
        selecArchivo.setFileFilter(new FileNameExtensionFilter("Plantilla Excel (*.xls)(*xlsx)", "xls","xlsx"));
    }
    
    public void buscarCliente() {
        try {
            if (tf_buscar.getText().length() >= 8 & tf_buscar.getText().length() <= 10) {
                EntityManagerFactory emf = Persistence.createEntityManagerFactory("LipiAppPU");
                EntityManager em = emf.createEntityManager();
                Cliente cli = new Cliente();
                TypedQuery<Cliente> consultaCliente = em.createNamedQuery("Cliente.findByRut", Cliente.class);
                consultaCliente.setParameter("rut", tf_buscar.getText());
                List<Cliente> lista = consultaCliente.getResultList();
                cli = lista.get(0);
                tf_rut.setText(cli.getRut());
                tf_nombre.setText(cli.getNombre());
                tf_domicilio.setText(cli.getDomicilio());

            } else if (tf_buscar.getText().length() <= 0) {
                JOptionPane.showMessageDialog(this, "Ingrese un RUT a buscar");
            } else if ((tf_buscar.getText().length() <= 6)) {
                JOptionPane.showMessageDialog(this, "Ingrese entre 8 y 10 carácteres");
            }
        } catch (Exception e) {
            if (e.equals(e)) {
                JOptionPane.showMessageDialog(this, "No existe Informacion! ");
            }
        }
    }
    
    public void modelarTabla() {
        /* hace referencia a mostrar los ingreso diario en la tabla */
        try {
            modelo = (new DefaultTableModel(null, new String[]{"ID", "Fecha", "N°Factura", "RUT", "Nombre", "Domicilio", "Valor", "5k", "11k", "15k", "45k", "15k Al", "15k Fe", "5k C", "11k C", "15k C", "45k C"}) {
                Class[] types = new Class[]{java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class};
                boolean[] canEdit = new boolean[]{false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false};

                @Override
                public Class getColumnClass(int columnIndex) {
                    return types[columnIndex];
                }

                @Override
                public boolean isCellEditable(int rowIndex, int colIndex) {
                    return canEdit[colIndex];
                }
            });
            tabla_cliente.setModel(modelo);
            tabla_cliente.getColumnModel().getColumn(0).setPreferredWidth(60);
            tabla_cliente.getColumnModel().getColumn(1).setPreferredWidth(80);
            tabla_cliente.getColumnModel().getColumn(2).setPreferredWidth(90);
            tabla_cliente.getColumnModel().getColumn(3).setPreferredWidth(100);
            tabla_cliente.getColumnModel().getColumn(4).setPreferredWidth(185);
            tabla_cliente.getColumnModel().getColumn(5).setPreferredWidth(200);
            tabla_cliente.getColumnModel().getColumn(6).setPreferredWidth(80);
            tabla_cliente.getColumnModel().getColumn(7).setPreferredWidth(50);
            tabla_cliente.getColumnModel().getColumn(8).setPreferredWidth(50);
            tabla_cliente.getColumnModel().getColumn(9).setPreferredWidth(50);
            tabla_cliente.getColumnModel().getColumn(10).setPreferredWidth(50);
            tabla_cliente.getColumnModel().getColumn(11).setPreferredWidth(50);
            tabla_cliente.getColumnModel().getColumn(12).setPreferredWidth(50);
            tabla_cliente.getColumnModel().getColumn(13).setPreferredWidth(50);
            tabla_cliente.getColumnModel().getColumn(14).setPreferredWidth(50);
            tabla_cliente.getColumnModel().getColumn(15).setPreferredWidth(50);
            tabla_cliente.getColumnModel().getColumn(16).setPreferredWidth(50);
            
            /*Object[] obj = new Object[17];
            ClienteJpaController jpa = new ClienteJpaController(Entity.getEntityManagerFactory());
            List<Cliente> uni = jpa.findClienteEntities();
            for (int i = 0; i < uni.size(); i++) {
                Cliente cli;
                cli = (Cliente) uni.get(i);
                obj[0] = cli.getId();
                obj[1] = cli.getFecha();
                obj[2] = cli.getFactura();
                obj[3] = cli.getRut();
                obj[4] = cli.getNombre();
                obj[5] = cli.getDomicilio();
                obj[6] = cli.getValorFactura();
                obj[7] = cli.getK();
                obj[8] = cli.getK1();
                obj[9] = cli.getK2();
                obj[10] = cli.getK3();
                obj[11] = cli.getKAl();
                obj[12] = cli.getKFe();
                obj[13] = cli.getKCat();
                obj[14] = cli.getKCat1();
                obj[15] = cli.getKCat2();
                obj[16] = cli.getKCat3();
                modelo.addRow(obj);
            }*/
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }
    
    private int validarVacio(){
        int cont = 
        tf_fecha.getText().length()*
        tf_factura.getText().length()*
        tf_rut.getText().length()*
        tf_nombre.getText().length()*
        tf_domicilio.getText().length()*
        tf_valor.getText().length()*
        tf_5k.getText().length()*
        tf_11k.getText().length()*
        tf_15k.getText().length()*
        tf_45k.getText().length()*
        tf_15kal.getText().length()*
        tf_15kFe.getText().length()*
        tf_5kc.getText().length()*
        tf_11kc.getText().length()*
        tf_15kc.getText().length()*
        tf_45kc.getText().length();
        return cont;
    }

    public void guardarRegistro() {
        if (validarVacio()!= 0) {
            Object[] opciones = {"Enviar", "Revisar"};
            int eleccion = JOptionPane.showOptionDialog(rootPane, "¿Desea Enviar la  Información?", "Mensaje de Confirmacion",
                    JOptionPane.YES_NO_OPTION,
                    JOptionPane.QUESTION_MESSAGE, null, opciones, "Aceptar");
            if (eleccion == JOptionPane.YES_OPTION) {
                try {
                    ClienteJpaController clienteController = new ClienteJpaController(Entity.getEntityManagerFactory());
                    Cliente cli = new Cliente();
                    cli.setFecha(tf_fecha.getText());
                    cli.setFactura(tf_factura.getText());
                    cli.setRut(tf_rut.getText());
                    cli.setNombre(tf_nombre.getText());
                    cli.setDomicilio(tf_domicilio.getText());
                    cli.setValorFactura(Integer.parseInt(tf_valor.getText()));
                    cli.setK(tf_5k.getText());
                    cli.setK1(tf_11k.getText());
                    cli.setK2(tf_15k.getText());
                    cli.setK3(tf_45k.getText());
                    cli.setKAl(tf_15kal.getText());
                    cli.setKFe(tf_15kFe.getText());
                    cli.setKCat(tf_5kc.getText());
                    cli.setKCat1(tf_11kc.getText());
                    cli.setKCat2(tf_15kc.getText());
                    cli.setKCat3(tf_45kc.getText());
                    clienteController.create(cli);

                    modelo.addRow(cli.toRow());
                    tabla_cliente.setModel(modelo);

                    JOptionPane.showMessageDialog(this, "Registro Ingresado!");
                    limpiar();
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(this, "Existen Campos vacios, por favor revisa tu información!");
                }
            }
        } else {
            JOptionPane.showMessageDialog(this, "Existen Campos vacios, por favor revisa tu información!");
        }
    }

    public void editarRegistro(Cliente c){
        int selec = tabla_cliente.getSelectedRow();
            modelo.setValueAt(c.getId(), selec, 0);
            modelo.setValueAt(c.getFecha(), selec, 1);
            modelo.setValueAt(c.getFactura(), selec, 2);
            modelo.setValueAt(c.getRut(), selec, 3);
            modelo.setValueAt(c.getNombre(), selec, 4);
            modelo.setValueAt(c.getDomicilio(), selec, 5);
            modelo.setValueAt(c.getValorFactura(), selec, 6);
            modelo.setValueAt(c.getK(), selec, 7);
            modelo.setValueAt(c.getK1(), selec, 8);
            modelo.setValueAt(c.getK2(), selec, 9);
            modelo.setValueAt(c.getK3(), selec, 10);
            modelo.setValueAt(c.getKAl(), selec, 11);
            modelo.setValueAt(c.getKFe(), selec, 12);
            modelo.setValueAt(c.getKCat(), selec, 13);
            modelo.setValueAt(c.getKCat1(), selec, 14);
            modelo.setValueAt(c.getKCat2(), selec, 15);
            modelo.setValueAt(c.getKCat3(), selec, 16);
    }
    
    public void eliminarRegistro() {
        try {
            Integer id = (Integer) tabla_cliente.getValueAt(tabla_cliente.getSelectedRow(), 0);
            ClienteJpaController prd = new ClienteJpaController(Entity.getEntityManagerFactory());
            int Confirmacion = JOptionPane.showConfirmDialog(this, "¿Desea eliminar?", "Confirmacion", JOptionPane.YES_NO_OPTION);
            if (Confirmacion == 0) {
                if (id != null) {
                    prd.destroy(id);
                    int fila = tabla_cliente.getSelectedRow();
                    if (fila >= 0) {
                        modelo.removeRow(fila);
                    }
                    JOptionPane.showMessageDialog(null, "Se ha eliminado el Registro");
                }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Seleccione un registro en el listado antes de eliminar");
        }
    }

    public void cargarRegistro(Cliente c) {
        lb_id.setText(c.getId().toString());
        tf_fecha.setText(c.getFecha());
        tf_factura.setText(c.getFactura());
        tf_rut.setText(c.getRut());
        tf_nombre.setText(c.getNombre());
        tf_domicilio.setText(c.getDomicilio());
        tf_valor.setText(c.getValorFactura().toString());
        tf_5k.setText(c.getK());
        tf_11k.setText(c.getK1());
        tf_15k.setText(c.getK2());
        tf_45k.setText(c.getK3());
        tf_15kal.setText(c.getKAl());
        tf_15kFe.setText(c.getKFe());
        tf_5kc.setText(c.getKCat());
        tf_11kc.setText(c.getKCat1());
        tf_15kc.setText(c.getKCat2());
        tf_45kc.setText(c.getKCat3());
    }

    public void limpiar() {
        lb_id.setText("");
        tf_fecha.setText(date);
        tf_factura.setText("");
        tf_rut.setText("");
        tf_nombre.setText("");
        tf_domicilio.setText("");
        tf_valor.setText("");
        tf_5k.setText("0");
        tf_11k.setText("0");
        tf_15k.setText("0");
        tf_45k.setText("0");
        tf_15kal.setText("0");
        tf_15kFe.setText("0");
        tf_5kc.setText("0");
        tf_11kc.setText("0");
        tf_15kc.setText("0");
        tf_45kc.setText("0");
    }

    public void soloNumeros(java.awt.event.KeyEvent evt) {
        char validar = evt.getKeyChar();
        if (Character.isLetter(validar)) {
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(rootPane, "Ingresa sólo digitos");
        }
    }

    public void exit(){
        Object [] opciones ={"Salir","Cancelar"};
        int eleccion = JOptionPane.showOptionDialog(rootPane,"¿Desea cerrar la aplicación?","Mensaje de Confirmacion",
        JOptionPane.YES_NO_OPTION,
        JOptionPane.QUESTION_MESSAGE,null,opciones,"Aceptar");
        if (eleccion == JOptionPane.YES_OPTION){
            System.exit(0);
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ingresos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ingresos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ingresos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ingresos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ingresos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.persistence.EntityManager Entity;
    private javax.swing.JButton bt_buscar;
    private javax.swing.JButton bt_editar;
    private javax.swing.JButton bt_eliminar;
    public javax.swing.JButton bt_exportar;
    private javax.swing.JButton bt_guardar;
    private javax.swing.JButton bt_guardarcambios;
    private javax.swing.JButton bt_importar;
    private javax.swing.JButton bt_limpiar;
    private javax.persistence.EntityManager em;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    public javax.swing.JPanel jPanel1;
    public javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    public javax.swing.JPanel jPanel4;
    public javax.swing.JPanel jPanel5;
    public javax.swing.JPanel jPanel6;
    public javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lb_id;
    public javax.swing.JTable tabla_cliente;
    private javax.swing.JTextField tf_11k;
    private javax.swing.JTextField tf_11kc;
    private javax.swing.JTextField tf_15k;
    private javax.swing.JTextField tf_15kFe;
    private javax.swing.JTextField tf_15kal;
    private javax.swing.JTextField tf_15kc;
    private javax.swing.JTextField tf_45k;
    private javax.swing.JTextField tf_45kc;
    private javax.swing.JTextField tf_5k;
    private javax.swing.JTextField tf_5kc;
    private javax.swing.JTextField tf_buscar;
    private javax.swing.JTextField tf_domicilio;
    private javax.swing.JTextField tf_factura;
    private javax.swing.JTextField tf_fecha;
    private javax.swing.JTextField tf_nombre;
    private javax.swing.JTextField tf_rut;
    private javax.swing.JTextField tf_valor;
    // End of variables declaration//GEN-END:variables
}
