/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Gui;

import controlladores.ClienteJpaController;
import Data.Cliente;
import java.awt.Image;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import javax.persistence.EntityManager;
import javax.persistence.EntityManagerFactory;
import javax.persistence.Persistence;
import javax.persistence.TypedQuery;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;

/**
 *
 * @author Theking
 */
public class Ingresos extends javax.swing.JFrame {

    /**
     * Creates new form Ingresos
     */
    public Ingresos() {
        initComponents();
        
        Image icon = new ImageIcon(getClass().getResource("/img/icon.jpg")).getImage();
        setIconImage(icon);
        
        this.setExtendedState(MAXIMIZED_BOTH);
        this.setDefaultCloseOperation(this.EXIT_ON_CLOSE);
        limpiar();
        mostrarTabla();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        Entity = java.beans.Beans.isDesignTime() ? null : javax.persistence.Persistence.createEntityManagerFactory("LipiAppPU").createEntityManager();
        Consulta = java.beans.Beans.isDesignTime() ? null : Entity.createQuery("SELECT c FROM Cliente c");
        query1 = java.beans.Beans.isDesignTime() ? null : Entity.createQuery("SELECT c FROM Cliente c");
        em = java.beans.Beans.isDesignTime() ? null : javax.persistence.Persistence.createEntityManagerFactory("LipiAppPU").createEntityManager();
        jPanel5 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        tf_buscar = new javax.swing.JTextField();
        bt_buscar = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        lb_id = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        tf_factura = new javax.swing.JTextField();
        tf_rut = new javax.swing.JTextField();
        tf_nombre = new javax.swing.JTextField();
        tf_domicilio = new javax.swing.JTextField();
        tf_valor = new javax.swing.JTextField();
        tf_fecha = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        Tabla_cliente = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        tf_5k = new javax.swing.JTextField();
        tf_11k = new javax.swing.JTextField();
        tf_15k = new javax.swing.JTextField();
        tf_45k = new javax.swing.JTextField();
        tf_15kal = new javax.swing.JTextField();
        tf_15kFe = new javax.swing.JTextField();
        tf_5kc = new javax.swing.JTextField();
        tf_15kc = new javax.swing.JTextField();
        tf_45kc = new javax.swing.JTextField();
        tf_11kc = new javax.swing.JTextField();
        bt_guardar = new javax.swing.JButton();
        bt_eliminar = new javax.swing.JButton();
        bt_editar = new javax.swing.JButton();
        bt_guardarcambios = new javax.swing.JButton();

        jLabel2.setText("jLabel2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("LipiApp");
        setName("Ingreso de clientes"); // NOI18N

        jLabel10.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        jLabel10.setText("Buscar Cliente");

        tf_buscar.setToolTipText("Ingrese RUT sin puntos ni guion");
        tf_buscar.setMaximumSize(new java.awt.Dimension(9, 9));

        bt_buscar.setText("Buscar");
        bt_buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_buscarActionPerformed(evt);
            }
        });

        lb_id.setEnabled(false);
        lb_id.setOpaque(true);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addComponent(lb_id, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lb_id, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(76, 76, 76)
                .addComponent(tf_buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(bt_buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap(23, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(tf_buscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt_buscar))
                .addGap(14, 14, 14))
            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jLabel1.setText("Fecha");

        jLabel3.setText("Numero Factura");

        jLabel4.setText("RUT");

        jLabel5.setText("Nombre completo");

        jLabel6.setText("Domicilio");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel7.setText("Valor de Factura");

        tf_factura.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tf_facturaKeyTyped(evt);
            }
        });

        tf_valor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tf_valorKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(96, 96, 96)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel3)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(65, 65, 65)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tf_fecha)
                    .addComponent(tf_domicilio, javax.swing.GroupLayout.DEFAULT_SIZE, 240, Short.MAX_VALUE)
                    .addComponent(tf_nombre)
                    .addComponent(tf_rut)
                    .addComponent(tf_factura)
                    .addComponent(tf_valor))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tf_fecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(tf_factura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(tf_rut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(tf_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(tf_domicilio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(tf_valor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Tabla_cliente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Fecha", "N° Factura", "RUT", "Nombre", "Domicilio", "Valor Factura", "5k", "11k", "15k", "45k", "15k Al", "15k FE", "5K C", "11k C", "15k C", "45kC"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        Tabla_cliente.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        Tabla_cliente.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(Tabla_cliente);
        if (Tabla_cliente.getColumnModel().getColumnCount() > 0) {
            Tabla_cliente.getColumnModel().getColumn(0).setResizable(false);
            Tabla_cliente.getColumnModel().getColumn(1).setResizable(false);
            Tabla_cliente.getColumnModel().getColumn(2).setResizable(false);
            Tabla_cliente.getColumnModel().getColumn(3).setResizable(false);
            Tabla_cliente.getColumnModel().getColumn(4).setResizable(false);
            Tabla_cliente.getColumnModel().getColumn(5).setResizable(false);
            Tabla_cliente.getColumnModel().getColumn(6).setResizable(false);
            Tabla_cliente.getColumnModel().getColumn(7).setResizable(false);
            Tabla_cliente.getColumnModel().getColumn(8).setResizable(false);
            Tabla_cliente.getColumnModel().getColumn(9).setResizable(false);
            Tabla_cliente.getColumnModel().getColumn(10).setResizable(false);
            Tabla_cliente.getColumnModel().getColumn(11).setResizable(false);
            Tabla_cliente.getColumnModel().getColumn(12).setResizable(false);
            Tabla_cliente.getColumnModel().getColumn(13).setResizable(false);
            Tabla_cliente.getColumnModel().getColumn(14).setResizable(false);
            Tabla_cliente.getColumnModel().getColumn(15).setResizable(false);
            Tabla_cliente.getColumnModel().getColumn(16).setResizable(false);
        }

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 1318, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(44, Short.MAX_VALUE))
        );

        jLabel12.setText("5k");
        jLabel12.setPreferredSize(new java.awt.Dimension(40, 14));

        jLabel13.setText("11k");
        jLabel13.setPreferredSize(new java.awt.Dimension(40, 14));

        jLabel14.setText("15k");
        jLabel14.setPreferredSize(new java.awt.Dimension(40, 14));

        jLabel15.setText("45k");
        jLabel15.setPreferredSize(new java.awt.Dimension(40, 14));

        jLabel16.setText("15k Al");
        jLabel16.setPreferredSize(new java.awt.Dimension(40, 14));

        jLabel17.setText("15k FE");
        jLabel17.setPreferredSize(new java.awt.Dimension(40, 14));

        jLabel18.setText("5k C");
        jLabel18.setPreferredSize(new java.awt.Dimension(40, 14));

        jLabel19.setText("11k C");
        jLabel19.setPreferredSize(new java.awt.Dimension(40, 14));

        jLabel20.setText("15k C");
        jLabel20.setPreferredSize(new java.awt.Dimension(40, 14));

        jLabel21.setText("45k C");
        jLabel21.setPreferredSize(new java.awt.Dimension(40, 14));

        tf_5k.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tf_5kKeyTyped(evt);
            }
        });

        tf_11k.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tf_11kKeyTyped(evt);
            }
        });

        tf_15k.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tf_15kKeyTyped(evt);
            }
        });

        tf_45k.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tf_45kKeyTyped(evt);
            }
        });

        tf_15kal.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tf_15kalKeyTyped(evt);
            }
        });

        tf_15kFe.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tf_15kFeKeyTyped(evt);
            }
        });

        tf_5kc.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tf_5kcKeyTyped(evt);
            }
        });

        tf_15kc.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tf_15kcKeyTyped(evt);
            }
        });

        tf_45kc.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tf_45kcKeyTyped(evt);
            }
        });

        tf_11kc.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tf_11kcKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(91, 91, 91)
                .addComponent(tf_5k, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(tf_11k, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(tf_15k, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(tf_45k, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21)
                .addComponent(tf_15kal, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(tf_15kFe, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(tf_5kc, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(tf_11kc, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(tf_15kc, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(tf_45kc, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(2, 2, 2)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf_11k, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_5k, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_15k, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_45k, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_15kal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_15kFe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_5kc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_15kc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_45kc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_11kc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        bt_guardar.setText("Guardar Información");
        bt_guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_guardarActionPerformed(evt);
            }
        });

        bt_eliminar.setText("Eliminar Información ");
        bt_eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_eliminarActionPerformed(evt);
            }
        });

        bt_editar.setText("Editar Información");
        bt_editar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_editarActionPerformed(evt);
            }
        });

        bt_guardarcambios.setText("Guardar cambios");
        bt_guardarcambios.setEnabled(false);
        bt_guardarcambios.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bt_guardarcambios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_guardarcambiosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(89, 89, 89)
                .addComponent(bt_guardar, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(bt_eliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(bt_guardarcambios, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(bt_editar, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(599, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                .addGap(94, 94, 94)
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21)
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23)
                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21)
                .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(jPanel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bt_guardar)
                    .addComponent(bt_eliminar)
                    .addComponent(bt_editar)
                    .addComponent(bt_guardarcambios))
                .addGap(313, 313, 313))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tf_facturaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf_facturaKeyTyped
        soloNumeros(evt);
    }//GEN-LAST:event_tf_facturaKeyTyped

    private void tf_valorKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf_valorKeyTyped
        soloNumeros(evt);
    }//GEN-LAST:event_tf_valorKeyTyped

    private void bt_buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_buscarActionPerformed
        buscar_cliente();
    }//GEN-LAST:event_bt_buscarActionPerformed

    private void bt_eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_eliminarActionPerformed
        eliminar();
        mostrarTabla();
    }//GEN-LAST:event_bt_eliminarActionPerformed

    private void bt_guardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_guardarActionPerformed
        Enviar_informacion();
    }//GEN-LAST:event_bt_guardarActionPerformed

    private void tf_11kcKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf_11kcKeyTyped
        soloNumeros(evt);
    }//GEN-LAST:event_tf_11kcKeyTyped

    private void tf_45kcKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf_45kcKeyTyped
        soloNumeros(evt);
    }//GEN-LAST:event_tf_45kcKeyTyped

    private void tf_15kcKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf_15kcKeyTyped
        soloNumeros(evt);
    }//GEN-LAST:event_tf_15kcKeyTyped

    private void tf_5kcKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf_5kcKeyTyped
        soloNumeros(evt);
    }//GEN-LAST:event_tf_5kcKeyTyped

    private void tf_15kFeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf_15kFeKeyTyped
        soloNumeros(evt);
    }//GEN-LAST:event_tf_15kFeKeyTyped

    private void tf_15kalKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf_15kalKeyTyped
        soloNumeros(evt);
    }//GEN-LAST:event_tf_15kalKeyTyped

    private void tf_45kKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf_45kKeyTyped
        soloNumeros(evt);
    }//GEN-LAST:event_tf_45kKeyTyped

    private void tf_15kKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf_15kKeyTyped
        soloNumeros(evt);
    }//GEN-LAST:event_tf_15kKeyTyped

    private void tf_11kKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf_11kKeyTyped
        soloNumeros(evt);
    }//GEN-LAST:event_tf_11kKeyTyped

    private void tf_5kKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf_5kKeyTyped
        soloNumeros(evt);
    }//GEN-LAST:event_tf_5kKeyTyped

    private void bt_editarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_editarActionPerformed
        try {
            ClienteJpaController jpa = new ClienteJpaController(em.getEntityManagerFactory());
            int select = Tabla_cliente.getSelectedRow();
            if (select != -1) {
                bt_guardarcambios.setEnabled(true);
                bt_guardar.setEnabled(false);
                bt_editar.setEnabled(false);
                bt_eliminar.setEnabled(false);
                int id = Integer.parseInt(Tabla_cliente.getValueAt(Tabla_cliente.getSelectedRow(), 0).toString());
                Cliente c = new Cliente();
                c = jpa.findCliente(id);
                cargarCliente(c);
            } else {
                JOptionPane.showMessageDialog(null,"Seleccione un registro de la lista");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null,"Seleccione un registro de la lista"+e.getMessage());
        }
    }//GEN-LAST:event_bt_editarActionPerformed

    private void bt_guardarcambiosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_guardarcambiosActionPerformed
        Object[] opciones = {"Guardar", "Cancelar"};
        int eleccion = JOptionPane.showOptionDialog(rootPane, "¿Desea guardar cambios?", "Mensaje de Confirmacion",
        JOptionPane.YES_NO_OPTION,
        JOptionPane.QUESTION_MESSAGE, null, opciones, "Aceptar");
        if (eleccion == JOptionPane.YES_OPTION) {
            try {
                ClienteJpaController clienteController = new ClienteJpaController(Entity.getEntityManagerFactory());
                Cliente cli = new Cliente();
                cli.setId(Integer.parseInt(lb_id.getText()));
                cli.setFecha(tf_fecha.getText());
                cli.setFactura(tf_factura.getText());
                cli.setRut(tf_rut.getText());
                cli.setNombre(tf_nombre.getText());
                cli.setDomicilio(tf_domicilio.getText());
                cli.setValorFactura(Integer.parseInt(tf_valor.getText()));
                cli.setK(tf_5k.getText());
                cli.setK1(tf_11k.getText());
                cli.setK2(tf_15k.getText());
                cli.setK3(tf_45k.getText());
                cli.setKAl(tf_15kal.getText());
                cli.setKFe(tf_15kFe.getText());
                cli.setKCat(tf_5kc.getText());
                cli.setKCat1(tf_11kc.getText());
                cli.setKCat2(tf_15kc.getText());
                cli.setKCat3(tf_45kc.getText());
                clienteController.edit(cli);
                mostrarTabla();
                limpiar();
                System.out.println(cli.toString());
                bt_guardarcambios.setEnabled(false);
                bt_guardar.setEnabled(true);
                bt_editar.setEnabled(true);
                bt_eliminar.setEnabled(true);

            } catch (Exception e) {
                if (e.equals(e)) {
                    JOptionPane.showMessageDialog(this, "Existen Campos vacios, por favor revisa tu información!");
                }
            }
        }
    }//GEN-LAST:event_bt_guardarcambiosActionPerformed
    
    public void mostrarTabla() {
    /* hace referencia a mostrar los ingreso diario en la tabla */
    try {
        DefaultTableModel modelo;

        modelo = (new DefaultTableModel(null, new String [] {"ID","Fecha","N°Factura","RUT","Nombre","Domicilio","Valor","5k","11k","15k","45k","15k Al","15k Fe","5k C","11k C","15k C","45k C"}){
            Class[] types = new Class [] {java.lang.String.class,java.lang.String.class,java.lang.String.class,java.lang.String.class,java.lang.String.class,java.lang.String.class,java.lang.String.class,java.lang.String.class,java.lang.String.class,java.lang.String.class,java.lang.String.class,java.lang.String.class,java.lang.String.class,java.lang.String.class,java.lang.String.class,java.lang.String.class,java.lang.String.class};
            boolean[] canEdit = new boolean [] {false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false};
            @Override
            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
            @Override
            public boolean isCellEditable(int rowIndex, int colIndex){
                return canEdit [colIndex];}
        });
        Tabla_cliente.setModel(modelo);
        Tabla_cliente.getColumnModel().getColumn(0).setPreferredWidth(60);
        Tabla_cliente.getColumnModel().getColumn(1).setPreferredWidth(80);
        Tabla_cliente.getColumnModel().getColumn(2).setPreferredWidth(90);
        Tabla_cliente.getColumnModel().getColumn(3).setPreferredWidth(100);
        Tabla_cliente.getColumnModel().getColumn(4).setPreferredWidth(200);
        Tabla_cliente.getColumnModel().getColumn(5).setPreferredWidth(200);
        Tabla_cliente.getColumnModel().getColumn(6).setPreferredWidth(80);
        Tabla_cliente.getColumnModel().getColumn(7).setPreferredWidth(50);
        Tabla_cliente.getColumnModel().getColumn(8).setPreferredWidth(50);
        Tabla_cliente.getColumnModel().getColumn(9).setPreferredWidth(50);
        Tabla_cliente.getColumnModel().getColumn(10).setPreferredWidth(50);
        Tabla_cliente.getColumnModel().getColumn(11).setPreferredWidth(50);
        Tabla_cliente.getColumnModel().getColumn(12).setPreferredWidth(50);
        Tabla_cliente.getColumnModel().getColumn(13).setPreferredWidth(50);
        Tabla_cliente.getColumnModel().getColumn(14).setPreferredWidth(50);
        Tabla_cliente.getColumnModel().getColumn(15).setPreferredWidth(50);
        Tabla_cliente.getColumnModel().getColumn(16).setPreferredWidth(50);
        Object[] obj = new Object[17];
        ClienteJpaController jpa = new ClienteJpaController(Entity.getEntityManagerFactory());

        List<Cliente> uni = jpa.findClienteEntities();
        Cliente cli = new Cliente();

        for (int i = 0; i < uni.size(); i++) {
            cli = (Cliente) uni.get(i);       
            obj[0]  = cli.getId();
            obj[1] = cli.getFecha();
            obj[2] = cli.getFactura();
            obj[3] = cli.getRut();
            obj[4] = cli.getNombre();
            obj[5] = cli.getDomicilio();
            obj[6] = cli.getValorFactura();
            obj[7] = cli.getK();
            obj[8] = cli.getK1();
            obj[9] = cli.getK2();
            obj[10] = cli.getK3();
            obj[11] = cli.getKAl();
            obj[12] = cli.getKFe();
            obj[13] = cli.getKCat();
            obj[14] = cli.getKCat1();
            obj[15] = cli.getKCat2();
            obj[16] = cli.getKCat3();
            modelo.addRow(obj);
        }
    } catch (Exception e) {
        JOptionPane.showMessageDialog(null, e.getMessage());
    }
}

    public void Enviar_informacion() {
        Object[] opciones = {"Enviar", "Revisar"};
        int eleccion = JOptionPane.showOptionDialog(rootPane, "¿Desea Enviar la  Información?", "Mensaje de Confirmacion",
        JOptionPane.YES_NO_OPTION,
        JOptionPane.QUESTION_MESSAGE, null, opciones, "Aceptar");
        if (eleccion == JOptionPane.YES_OPTION) {
            try {
                ClienteJpaController clienteController = new ClienteJpaController(Entity.getEntityManagerFactory());
                Cliente cli = new Cliente();
                cli.setFecha(tf_fecha.getText());
                cli.setFactura(tf_factura.getText());
                cli.setRut(tf_rut.getText());
                cli.setNombre(tf_nombre.getText());
                cli.setDomicilio(tf_domicilio.getText());
                cli.setValorFactura(Integer.parseInt(tf_valor.getText()));
                cli.setK(tf_5k.getText());
                cli.setK1(tf_11k.getText());
                cli.setK2(tf_15k.getText());
                cli.setK3(tf_45k.getText());
                cli.setKAl(tf_15kal.getText());
                cli.setKFe(tf_15kFe.getText());
                cli.setKCat(tf_5kc.getText());
                cli.setKCat1(tf_11kc.getText());
                cli.setKCat2(tf_15kc.getText());
                cli.setKCat3(tf_45kc.getText());
                clienteController.create(cli);
                mostrarTabla();
                limpiar();
                JOptionPane.showMessageDialog(this, "Registro Ingresado!");
            } catch (Exception e) {
                if (e.equals(e)) {
                    JOptionPane.showMessageDialog(this, "Existen Campos vacios, por favor revisa tu información!");
                }
            }
        } else {

        }
    }

    public void buscar_cliente() {
        if (tf_buscar.getText().length() >= 8 & tf_buscar.getText().length() <= 10) {
            try {
                EntityManagerFactory emf = Persistence.createEntityManagerFactory("LipiAppPU");
                EntityManager em = emf.createEntityManager();
                Cliente cli = new Cliente();

                TypedQuery<Cliente> consultaCliente = em.createNamedQuery("Cliente.findByRut", Cliente.class);
                consultaCliente.setParameter("rut", tf_buscar.getText());
                List<Cliente> lista = consultaCliente.getResultList();

                cli = lista.get(0);

                tf_rut.setText(cli.getRut());
                tf_nombre.setText(cli.getNombre());
                tf_domicilio.setText(cli.getDomicilio());

            } catch (Exception e) {
                if (e.equals(e)) {
                    JOptionPane.showMessageDialog(this, "No existe Informacion! " + e.getMessage());
                }
            }
        } else if (tf_buscar.getText().length() <= 0) {

            JOptionPane.showMessageDialog(this, "Ingrese un RUT a buscar");

        } else if ((tf_buscar.getText().length() <= 6)) {
            JOptionPane.showMessageDialog(this, "Ingrese entre 8 y 10 carácteres");
        }
    }

    public void eliminar(){
        try {
            Integer id = (Integer) Tabla_cliente.getValueAt(Tabla_cliente.getSelectedRow(), 0);     
            ClienteJpaController prd = new ClienteJpaController(Entity.getEntityManagerFactory());
            int Confirmacion = JOptionPane.showConfirmDialog(this, "¿Desea eliminar?", "Confirmacion", JOptionPane.YES_NO_OPTION);
              if (Confirmacion == 0) {
                    if (id != null) {
                        prd.destroy(id);
                        this.mostrarTabla();
                        JOptionPane.showMessageDialog(null, "Se ha eliminado el Registro");
                    } 
                }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Seleccione un registro en el listado antes de eliminar");
        }
    }

    public void cargarCliente(Cliente c){
        lb_id.setText(c.getId().toString());
        tf_fecha.setText(c.getFecha());
        tf_factura.setText(c.getFactura());
        tf_rut.setText(c.getRut());
        tf_nombre.setText(c.getNombre());
        tf_domicilio.setText(c.getDomicilio());
        tf_valor.setText(c.getValorFactura().toString());
        tf_5k.setText(c.getK());
        tf_11k.setText(c.getK1());
        tf_15k.setText(c.getK2());
        tf_45k.setText(c.getK3());
        tf_15kal.setText(c.getKAl());
        tf_15kFe.setText(c.getKFe());
        tf_5kc.setText(c.getKCat());
        tf_11kc.setText(c.getKCat1());
        tf_15kc.setText(c.getKCat2());
        tf_45kc.setText(c.getKCat3());
    }
    
    public void limpiar() {
        Date fecha = new Date();
        SimpleDateFormat dt1 = new SimpleDateFormat("dd-MM-yyyy");
        lb_id.setText("");
        tf_fecha.setText(dt1.format(fecha));
        tf_factura.setText("");
        tf_rut.setText("");
        tf_nombre.setText("");
        tf_domicilio.setText("");
        tf_valor.setText("");
        tf_5k.setText("0");
        tf_11k.setText("0");
        tf_15k.setText("0");
        tf_45k.setText("0");
        tf_15kal.setText("0");
        tf_15kFe.setText("0");
        tf_5kc.setText("0");
        tf_11kc.setText("0");
        tf_15kc.setText("0");
        tf_45kc.setText("0");
    }
    
    public void soloNumeros(java.awt.event.KeyEvent evt) {
        char validar = evt.getKeyChar();
        if (Character.isLetter(validar)) {
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(rootPane, "Ingresa sólo digitos");
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ingresos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ingresos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ingresos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ingresos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ingresos().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.persistence.Query Consulta;
    private javax.persistence.EntityManager Entity;
    private javax.swing.JTable Tabla_cliente;
    private javax.swing.JButton bt_buscar;
    private javax.swing.JButton bt_editar;
    private javax.swing.JButton bt_eliminar;
    private javax.swing.JButton bt_guardar;
    private javax.swing.JButton bt_guardarcambios;
    private javax.persistence.EntityManager em;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lb_id;
    private javax.persistence.Query query1;
    private javax.swing.JTextField tf_11k;
    private javax.swing.JTextField tf_11kc;
    private javax.swing.JTextField tf_15k;
    private javax.swing.JTextField tf_15kFe;
    private javax.swing.JTextField tf_15kal;
    private javax.swing.JTextField tf_15kc;
    private javax.swing.JTextField tf_45k;
    private javax.swing.JTextField tf_45kc;
    private javax.swing.JTextField tf_5k;
    private javax.swing.JTextField tf_5kc;
    private javax.swing.JTextField tf_buscar;
    private javax.swing.JTextField tf_domicilio;
    private javax.swing.JTextField tf_factura;
    private javax.swing.JTextField tf_fecha;
    private javax.swing.JTextField tf_nombre;
    private javax.swing.JTextField tf_rut;
    private javax.swing.JTextField tf_valor;
    // End of variables declaration//GEN-END:variables
}
